all:

task0:
	gcc -c task0.c
	gcc -o task0 task0.c -lm
	clear
	./task0
	rm -rf task0.o task0

task1:
	gcc -c task1.c
	gcc -o task1 task1.c -lm
	clear
	./task1
	rm -rf task1.o task1

task2:
	gcc -c task2.c
	gcc -o task2 task2.c -lm
	clear
	./task2
	rm -rf task2.o task2

task3:
	gcc -c task3.c
	gcc -o task3 task3.c -lm
	clear
	./task3
	rm -rf task3.o task3

task4:
	gcc -c task4.c
	gcc -o task4 task4.c -lm
	clear
	./task4
	rm -rf task4.o task4

task5:
	gcc -c task5.c
	gcc -o task5 task5.c -lm
	clear
	./task5
	rm -rf task5.o task5

task6:
	gcc -c task6.c
	gcc -o task6 task6.c -lm
	clear
	./task6
	rm -rf task6.o task6
